# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2

      - name: Setup .npmrc file to publish to npm
        uses: actions/setup-node@v2
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Lint the project (part 1)
        uses: ./lint.yml
      
      - name: Build the project (part 1)
        uses: ./build.yml

      - name: Lint the project (part 2)
        run: npm run lint
        
      - name: Build the project (part 2)
        run: npm run build
      
      - name: Update changelog
        run: printf '# ${{ github.event.release.name }} \n## ${{ github.event.release.tag_name }} \n ${{ github.event.release.body }} \n\n***\n'$(cat ../../CHANGELOG.md)''

      - name: update package version
        run: npm version ${{ github.event.release.tag_name }}

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
